apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mz
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:muzashi777/argo-app.git
    targetRevision: main
    path: app
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true